version: '3.9'

services:
  db:
    image: postgres:17-alpine
    container_name: student_course_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: student_course_backend
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: student_course_frontend
    restart: always
    ports:
      - "4173:4173"
    depends_on:
      - backend

volumes:
  pgdata: