version: '3.9'

services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: student_course_backend
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: student_course_frontend
    restart: always
    ports:
      - "4173:4173"
    depends_on:
      - backend
